Add a variable to control Lambda timeout
nsbno/terraform-aws-single-use-fargate-task pull request #12
Opened 2020-06-26 11:20 UTC by stekern

Sometimes the Lambda fails because it runs a little bit longer than the default Lambda timeout of 3 seconds. I suggest we up this to at least 10 seconds, and make it controllable through an optional input variable.

2020-06-26 11:49 UTC, colincoleman requested changes
Looks good in principal - just a question on why 10s?

2020-06-26 11:49 UTC, colincoleman commented on variables.tf
> +  default     = 10
Why not the standard 3 second timeout?

2020-06-26 11:51 UTC, colincoleman commented on variables.tf
> +  default     = 10
Ah I missed the comment above....

2020-06-26 11:51 UTC, colincoleman approved these changes

2020-06-29 08:42 UTC, stekern commented
No specific reason for using 10 besides it not being too low or too high :man_shrugging: 5 would probably be enough, but 10 feels like a safer and more future-proof value

2020-06-29 13:18 UTC, merged